### ISSUE TITLE
Can not load testup/core.rb for release 2.2

### ISSUE THREAD

**Issue by saedrna** [SketchUp/testup-2#152]
I have the following error code related to minitest. Furthermore, even if I manualy put minitest in the directory parallel to testup.rb, the test can load (e.g. show in the test dialog), but still can not run.

```
Error: #<Gem::UnsatisfiableDependencyError: Unable to resolve dependency: user requested 'minitest (= 5.4.3)'>
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/resolver/installer_set.rb:70:in `add_always_install'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/dependency_installer.rb:463:in `resolve_dependencies'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/dependency_installer.rb:373:in `install'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems.rb:558:in `install'
D:/build-src/testup-2/src/testup/core.rb:21:in `rescue in <top (required)>'
D:/build-src/testup-2/src/testup/core.rb:15:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2018/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2018/Tools/extensions.rb:197:in `load'
D:/build-src/testup-2/src/testup.rb:42:in `register_extension'
D:/build-src/testup-2/src/testup.rb:42:in `<module:TestUp>'
D:/build-src/testup-2/src/testup.rb:17:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Users/huhan/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/load_osketch.rb:5:in `<top (required)>'
```

Is there a solution for this？

Han

**Comment by saedrna** [comment]
I have found a workaround, this is because my machine can not work for code like ```gem 'minitest'```, therefore I comment this kind of code and manually put minitest in place it can be searched, e.g. in core.rb and minitest_setup.rb

**Comment by thomthom** [comment]
Why doesn't your machine work with `gem 'minitest'`?

**Comment by saedrna** [comment]
I don't know. In fact, my laptop works but not for the desktop above.
When it works, it will create gems in the place below,

![tim 20180622235553](https://user-images.githubusercontent.com/3850191/41786388-efb9f48e-7677-11e8-8061-b4186718f3c9.png)

**Comment by thomthom** [comment]
Hm... strange. It works on all the machines I've used and tested on as well. First time I've heard of it failing.

@MSP-Greg - any ideas?

**Comment by MSP-Greg** [comment]
@saedrna

RubyGems normally places gems in `Gem.dir`.  Also, the value of `env["GEM_HOME"]` can affect it.

Can you see if both systems have similar values?

**Comment by saedrna** [comment]
The below message is from an OK computer (my laptop). For the computer not capable to install (my office desktop), I will test when I return. The installation is good.
```
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> Gem.install('minitest', '5.4.3')
Fetching: minitest-5.4.3.gem (100%)
=> [#<Gem::Specification:0x00000000056a6a58 @extension_dir="C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/minitest-5.4.3", @full_gem_path="C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.4.3", @cache_file=nil, @gems_dir="C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems", @base_dir="C:/Ruby24-x64/lib/ruby/gems/2.4.0", @loaded_from="C:/Ruby24-x64/lib/ruby/gems/2.4.0/specifications/minitest-5.4.3.gemspec", @original_platform="ruby", @installed_by_version=#<Gem::Version "2.7.7">, @autorequire=nil, @description="minitest provides a complete suite of testing facilities supporting\nTDD, BDD, mocking, and benchmarking.\n\n    \"I had a class with Jim Weirich on testing last week and we were\n     allowed to choose our testing frameworks. Kirk Haines and I were\n     paired up and we cracked open the code for a few test\n     frameworks...\n\n     I MUST say that minitest is *very* readable / understandable\n     compared to the 'other two' options we looked at. Nicely done and\n     thank you for helping us keep our mental sanity.\"\n\n    -- Wayne E. Seguin\n\nminitest/unit is a small and incredibly fast unit testing framework.\nIt provides a rich set of assertions to make your tests clean and\nreadable.\n\nminitest/spec is a functionally complete spec engine. It hooks onto\nminitest/unit and seamlessly bridges test assertions over to spec\nexpectations.\n\nminitest/benchmark is an awesome way to assert the performance of your\nalgorithms in a repeatable manner. Now you can assert that your newb\nco-worker doesn't replace your linear algorithm with an exponential\none!\n\nminitest/mock by Steven Baker, is a beautifully tiny mock (and stub)\nobject framework.\n\nminitest/pride shows pride in testing and adds coloring to your test\noutput. I guess it is an example of how to write IO pipes too. :P\n\nminitest/unit is meant to have a clean implementation for language\nimplementors that need a minimal set of methods to bootstrap a working\ntest suite. For example, there is no magic involved for test-case\ndiscovery.\n\n    \"Again, I can't praise enough the idea of a testing/specing\n     framework that I can actually read in full in one sitting!\"\n\n    -- Piotr Szotkowski\n\nComparing to rspec:\n\n    rspec is a testing DSL. minitest is ruby.\n\n    -- Adam Hawkins, \"Bow Before MiniTest\"\n\nminitest doesn't reinvent anything that ruby already provides, like:\nclasses, modules, inheritance, methods. This means you only have to\nlearn ruby to use minitest and all of your regular OO practices like\nextract-method refactorings still apply.", @email=["ryand-ruby@zenspider.com"], @homepage="https://github.com/seattlerb/minitest", @name="minitest", @post_install_message=nil, @rubyforge_project=nil, @signing_key=nil, @summary="minitest provides a complete suite of testing facilities supporting TDD, BDD, mocking, and benchmarking", @version=#<Gem::Version "5.4.3">, @authors=["Ryan Davis"], @bindir="bin", @cert_chain=["-----BEGIN CERTIFICATE-----\nMIIDPjCCAiagAwIBAgIBAjANBgkqhkiG9w0BAQUFADBFMRMwEQYDVQQDDApyeWFu\nZC1ydWJ5MRkwFwYKCZImiZPyLGQBGRYJemVuc3BpZGVyMRMwEQYKCZImiZPyLGQB\nGRYDY29tMB4XDTE0MDkxNzIzMDcwN1oXDTE1MDkxNzIzMDcwN1owRTETMBEGA1UE\nAwwKcnlhbmQtcnVieTEZMBcGCgmSJomT8ixkARkWCXplbnNwaWRlcjETMBEGCgmS\nJomT8ixkARkWA2NvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALda\nb9DCgK+627gPJkB6XfjZ1itoOQvpqH1EXScSaba9/S2VF22VYQbXU1xQXL/WzCkx\ntaCPaLmfYIaFcHHCSY4hYDJijRQkLxPeB3xbOfzfLoBDbjvx5JxgJxUjmGa7xhcT\noOvjtt5P8+GSK9zLzxQP0gVLS/D0FmoE44XuDr3iQkVS2ujU5zZL84mMNqNB1znh\nGiadM9GHRaDiaxuX0cIUBj19T01mVE2iymf9I6bEsiayK/n6QujtyCbTWsAS9Rqt\nqhtV7HJxNKuPj/JFH0D2cswvzznE/a5FOYO68g+YCuFi5L8wZuuM8zzdwjrWHqSV\ngBEfoTEGr7Zii72cx+sCAwEAAaM5MDcwCQYDVR0TBAIwADALBgNVHQ8EBAMCBLAw\nHQYDVR0OBBYEFEfFe9md/r/tj/Wmwpy+MI8d9k/hMA0GCSqGSIb3DQEBBQUAA4IB\nAQAFoDJRokCQdxFfOrmsKX41KOFlU/zjrbDVM9hgB/Ur999M6OXGSi8FitXNtMwY\nFVjsiAPeU7HaWVVcZkj6IhINelTkXsxgGz/qCzjHy3iUMuZWw36cS0fiWJ5rvH+e\nhD7uXxJSFuyf1riDGI1aeWbQ74WMwvNstOxLUMiV5a1fzBhlxPqb537ubDjq/M/h\nzPUFPVYeL5KjDHLCqI2FwIk2sEMOQgjpXHzl+3NlD2LUgUhHDMevmgVua0e2GT1B\nxJcC6UN6NHMOVMyAXsr2HR0gRRx4ofN1LoP2KhXzSr8UMvQYlwPmE0N5GQv1b5AO\nVpzF30vNaJK6ZT7xlIsIlwmH\n-----END CERTIFICATE-----\n"], @date=2014-11-11 00:00:00 UTC, @dependencies=[<Gem::Dependency type=:development name="rdoc" requirements="~> 4.0">, <Gem::Dependency type=:development name="hoe" requirements="~> 3.13">], @executables=[], @extensions=[], @extra_rdoc_files=["History.txt", "Manifest.txt", "README.txt"], @files=[".autotest", ".gemtest", "History.txt", "Manifest.txt", "README.txt", "Rakefile", "design_rationale.rb", "lib/hoe/minitest.rb", "lib/minitest.rb", "lib/minitest/assertions.rb", "lib/minitest/autorun.rb", "lib/minitest/benchmark.rb", "lib/minitest/expectations.rb", "lib/minitest/hell.rb", "lib/minitest/mock.rb", "lib/minitest/parallel.rb", "lib/minitest/pride.rb", "lib/minitest/pride_plugin.rb", "lib/minitest/spec.rb", "lib/minitest/test.rb", "lib/minitest/unit.rb", "test/minitest/metametameta.rb", "test/minitest/test_minitest_benchmark.rb", "test/minitest/test_minitest_mock.rb", "test/minitest/test_minitest_reporter.rb", "test/minitest/test_minitest_spec.rb", "test/minitest/test_minitest_unit.rb"], @licenses=["MIT"], @metadata={}, @platform="ruby", @rdoc_options=["--main", "README.txt"], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x0000000005694178 @requirements=[[">=", #<Gem::Version "0">]]>, @required_rubygems_version=#<Gem::Requirement:0x000000000568f8f8 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="2.4.1", @specification_version=4, @test_files=["test/minitest/test_minitest_benchmark.rb", "test/minitest/test_minitest_mock.rb", "test/minitest/test_minitest_reporter.rb", "test/minitest/test_minitest_spec.rb", "test/minitest/test_minitest_unit.rb"], @new_platform="ruby", @full_name="minitest-5.4.3" minitest-5.4.3>]
irb(main):003:0>
```
